# Function 8

In [11]:
from scipy.optimize import differential_evolution, basinhopping

# Define the objective function as provided in the user's image
def function8(x):
    out = -2 * (x[0] - 0.1)**2
    out += -1 * (x[1] - 0.15)**2
    out += -3 * (x[2] - 0.13)**2
    out += -1 * (x[3] - 0.15)**2
    out += -0.5 * (x[4] - 0.8)**2
    out += -1 * (x[5] - 0.5)**2
    out += -2 * (x[6] - 0.2)**2
    out += -0.1 * (x[7] - 0.6)**2
    return out + 10

# Set the bounds for each dimension
bounds = [(0, 1)] * 8  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function8, bounds)

# Perform basinhopping
result_bh = basinhopping(function8, [0.5] * 8, niter=200)  # start at the middle of the bounds

result_de, result_bh.fun, result_bh.x



( message: Optimization terminated successfully.
  success: True
      fun: 2.778299999999999
        x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  0.000e+00
             0.000e+00  1.000e+00  0.000e+00]
      nit: 83
     nfev: 10098
      jac: [-3.600e+00 -1.700e+00 -5.220e+00 -1.700e+00  8.000e-01
             1.000e+00 -3.200e+00  1.200e-01],
 -1.7499604271971958e+25,
 array([ 3.68952760e+07,  8.10047148e+06, -2.16893163e+12,  1.84032906e+12,
        -1.74163846e+06, -2.75404585e+03,  2.77150904e+07, -2.20368002e+04]))

In [2]:
# Sample inputs for the function
x_samples = [
    [0.1, 0.15, 0.13, 0.15, 0.8, 0.5, 0.2, 0.6]
]

# Define the objective function as provided in the user's image
def function8(x):
    out = -2 * (x[0] - 0.1)**2
    out += -1 * (x[1] - 0.15)**2
    out += -3 * (x[2] - 0.13)**2
    out += -1 * (x[3] - 0.15)**2
    out += -0.5 * (x[4] - 0.8)**2
    out += -1 * (x[5] - 0.5)**2
    out += -2 * (x[6] - 0.2)**2
    out += -0.1 * (x[7] - 0.6)**2
    return out + 10

# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function8(x)
    print(f'Function value for {x}:', function_value)

Function value for [0.1, 0.15, 0.13, 0.15, 0.8, 0.5, 0.2, 0.6]: 10.0


# Function 7

In [12]:
import numpy as np
from scipy.optimize import differential_evolution, basinhopping

def function7(x):
    alpha = np.array([1.0, 1.2, 3.0, 3.2])
    A = np.array([
        [10, 3, 17, 3.50, 1.7, 8],
        [0.05, 10, 17, 0.1, 8, 14],
        [3, 3.5, 1.7, 10, 17, 8],
        [17, 8, 0.05, 10, 0.1, 14]
    ])
    P = 10**-4 * np.array([
        [1312, 1696, 5569, 124, 8283, 5886],
        [2329, 4135, 8307, 3736, 1004, 9991],
        [2348, 1451, 3522, 2883, 3047, 6650],
        [4047, 8828, 8732, 5743, 1091, 381]
    ])
    
    external_sum = 0
    for i in range(4):
        internal_sum = 0
        for j in range(6):
            internal_sum += A[i][j] * (x[j] - P[i][j])**2
        external_sum += alpha[i] * np.exp(-internal_sum)
    
    return -external_sum

# Set the bounds for each dimension
bounds = [(0, 1)] * 6  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function7, bounds)

# Perform basinhopping
result_bh = basinhopping(function7, [0.5] * 8, niter=200)  # start at the middle of the bounds

result_de, result_bh.fun, result_bh.x



( message: Optimization terminated successfully.
  success: True
      fun: -3.2031619177893287
        x: [ 4.047e-01  8.824e-01  8.461e-01  5.740e-01  1.389e-01
             3.850e-02]
      nit: 18
     nfev: 1871
      jac: [-1.940e-04  8.828e-05 -4.041e-06 -9.339e-05 -8.038e-06
             1.990e-04],
 -3.3223680114155085,
 array([ 0.2016895 ,  0.15001068,  0.47687397,  0.27533243,  0.31165161,
         0.65730053, -3.01501665,  3.90244459]))

In [14]:
best_point = [0.2016895, 0.15001069, 0.47687396, 0.27533243, 0.31165162, 0.65730053]
exploitation_range = 0.05  # 5%

bounds_exploitation = [(x - x * exploitation_range, x + x * exploitation_range) for x in best_point]


In [15]:
# Perform differential evolution
result_de = differential_evolution(function7, bounds_exploitation)

# Perform basinhopping
result_bh = basinhopping(function7, [0.5] * 8, niter=200)  # start at the middle of the bounds

result_de, result_bh.fun, result_bh.x

( message: Optimization terminated successfully.
  success: True
      fun: -3.322368011415493
        x: [ 2.017e-01  1.500e-01  4.769e-01  2.753e-01  3.117e-01
             6.573e-01]
      nit: 1
     nfev: 257
      jac: [ 1.776e-07 -2.665e-07 -4.441e-07 -1.332e-07 -4.441e-07
            -4.885e-07],
 -3.3223680114155076,
 array([ 0.2016895 ,  0.15001068,  0.47687397,  0.27533242,  0.31165161,
         0.65730053,  3.35894765, -0.98489902]))

In [13]:
# Sample inputs for the function
x_samples = [
    [0.215055, 0.156395, 0.470335, 0.277514, 0.312339, 0.658909],
    [0.2016895 , 0.15001069, 0.47687396, 0.27533243, 0.31165162,
        0.65730053, 1.48950059, 4.05739046]
]


# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function7(x)
    print(f'Function value for {x}:', function_value)

Function value for [0.215055, 0.156395, 0.470335, 0.277514, 0.312339, 0.658909]: -3.3192764124650775
Function value for [0.2016895, 0.15001069, 0.47687396, 0.27533243, 0.31165162, 0.65730053, 1.48950059, 4.05739046]: -3.3223680114155094


# Function 6

In [9]:
import numpy as np
from scipy.optimize import differential_evolution

# Define function6 from the image provided with added noise
def function6(x):
    out = -1 * np.abs(x[0] - 0.42)
    out += -1 * np.abs(x[1] - 0.36)
    out += -1 * np.abs(x[2] - 0.65)
    out += -1 * np.abs(x[3] - 0.77)
    out += -1 * np.abs(x[4] - 0.1)
    return out + np.random.normal(0, 0.05)

# Since we are looking for global optima and the function is noisy,
# we should run the optimizer several times to ensure we find a robust solution.
# We'll define the bounds for the optimization (assuming they are [0, 1] for each variable)
bounds = [(0, 1), (0, 1), (0, 1), (0, 1), (0, 1)]

# Perform the optimization using Differential Evolution
# Due to the stochastic nature of the function, it's recommended to increase the number of iterations and
# the population size to get a more accurate result.
result = differential_evolution(function6, bounds, maxiter=1000, popsize=25)

result.fun, result.x



(-3.6196662283652015,
 array([0.99377466, 0.99638798, 0.01748738, 0.00609115, 0.98995587]))

In [3]:
import numpy as np
from scipy.optimize import differential_evolution

# Define function6 from the image provided with added noise
def function6(x):
    out = -1 * np.abs(x[0] - 0.42)
    out += -1 * np.abs(x[1] - 0.36)
    out += -1 * np.abs(x[2] - 0.65)
    out += -1 * np.abs(x[3] - 0.77)
    out += -1 * np.abs(x[4] - 0.1)
    return out + np.random.normal(0, 0.05)

# New bounds based on the optimization results
bounds = [(0.99, 1.0),  # New bound for x[0]
          (0.97, 1.0),  # New bound for x[1]
          (0.0, 0.05),  # New bound for x[2]
          (0.0, 0.05),  # New bound for x[3]
          (0.97, 1.0)]  # New bound for x[4]

# Perform the optimization using Differential Evolution with the new bounds
result = differential_evolution(function6, bounds, maxiter=10000, popsize=1000)

result.fun, result.x

(-3.68461671048986,
 array([0.99821647, 0.97882707, 0.01156669, 0.02451674, 0.98599329]))

In [9]:
import numpy as np

# Sample inputs for the function
x_samples = [
    [0.999999, 0.999031, 0.003125, 0.      , 0.992245],
    [0.99572389, 0.97373593, 0.0027237 , 0.00847641, 0.98693783],
    [0.99881636, 0.99261304, 0.01461281, 0.03374769, 0.97225405],
    [0.99377466, 0.99638798, 0.01748738, 0.00609115, 0.98995587],
    [9.98270807e-01, 9.90335660e-01, 1.10511377e-02, 7.30842077e-04,
        9.89654110e-01],
    [0.99704482, 0.99243628, 0.01288065, 0.02471047, 0.99574526],
    [0.99333672, 0.99717332, 0.00717687, 0.01454184, 0.98702172],
    [9.94885225e-01, 9.82954887e-01, 2.14005077e-02, 9.82798925e-04,
        9.99218603e-01],
    [9.92826750e-01, 9.78115507e-01, 3.58238894e-04, 2.45893403e-02,
        9.94932078e-01],
    [0.99185211, 0.99143621, 0.00726933, 0.00358599, 0.99696841],
    [0.99498962, 0.99866151, 0.00269336, 0.01282776, 0.99915352],
    [0.99981685, 0.99954416, 0.00292226, 0.00500321, 0.99681116],
    [0.99821647, 0.97882707, 0.01156669, 0.02451674, 0.98599329]
]

# Define function6 from the image provided with added noise
def function6(x):
    out = -1 * np.abs(x[0] - 0.42)
    out += -1 * np.abs(x[1] - 0.36)
    out += -1 * np.abs(x[2] - 0.65)
    out += -1 * np.abs(x[3] - 0.77)
    out += -1 * np.abs(x[4] - 0.1)
    return out + np.random.normal(0, 0.05)
    return out + 10

# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function6(x)
    print(f'Function value for {x}:', function_value)
    
x_samples_array = np.array(x_samples)

# Compute the average of each dimension
dimension_averages = np.mean(x_samples_array, axis=0)
dimension_averages

Function value for [0.999999, 0.999031, 0.003125, 0.0, 0.992245]: -3.550547793816232
Function value for [0.99572389, 0.97373593, 0.0027237, 0.00847641, 0.98693783]: -3.447025695773189
Function value for [0.99881636, 0.99261304, 0.01461281, 0.03374769, 0.97225405]: -3.538055520338465
Function value for [0.99377466, 0.99638798, 0.01748738, 0.00609115, 0.98995587]: -3.5193434175063634
Function value for [0.998270807, 0.99033566, 0.0110511377, 0.000730842077, 0.98965411]: -3.4958947505685853
Function value for [0.99704482, 0.99243628, 0.01288065, 0.02471047, 0.99574526]: -3.421812246468627
Function value for [0.99333672, 0.99717332, 0.00717687, 0.01454184, 0.98702172]: -3.497467298804368
Function value for [0.994885225, 0.982954887, 0.0214005077, 0.000982798925, 0.999218603]: -3.423910895933074
Function value for [0.99282675, 0.978115507, 0.000358238894, 0.0245893403, 0.994932078]: -3.4687717154749667
Function value for [0.99185211, 0.99143621, 0.00726933, 0.00358599, 0.99696841]: -3.51275

array([0.99611948, 0.99009635, 0.00886676, 0.01229263, 0.9912993 ])

# Function 5

In [18]:
import numpy as np
from scipy.optimize import differential_evolution, basinhopping

def function5 (x, b=[8, 18, 44, 114]):
    """
    Power Sum function for 4-dimensional input.

    Args:
    - x: A list or array of 4 variables.
    - b: A list of constants for the Power Sum function.

    Returns:
    - The value of the Power Sum function at the point x.
    """
    d = 4  # Number of dimensions
    if len(x) != d or len(b) != d:
        raise ValueError(f"Input vector x and constant vector b must both be of length {d}.")
    
    return sum((sum(x_j ** (i+1) for x_j in x) - b[i]) ** 2 for i in range(d))


# Set the bounds for each dimension
bounds = [(0, 1)] * 4  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function5, bounds)

# Perform basinhopping
result_bh = basinhopping(function5, [0.5] * 4, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")

result_de =  message: Optimization terminated successfully.
 success: True
     fun: 13912.0
       x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00]
     nit: 10
    nfev: 670
     jac: [-1.184e+03 -1.184e+03 -1.184e+03 -1.184e+03], result_bh.fun = 1.1647759294808782e-10, result_bh.x = [0.99998856 2.99999767 1.99904125 2.00096658]


In [19]:
best_point = [1, 1, 1, 1]
exploitation_range = 0.05  # 5%

bounds_exploitation = [(x - x * exploitation_range, x + x * exploitation_range) for x in best_point]


In [20]:
# Perform differential evolution
result_de = differential_evolution(function5, bounds_exploitation)

# Perform basinhopping
result_bh = basinhopping(function5, [0.5] * 4, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")

result_de =  message: Optimization terminated successfully.
 success: True
     fun: 13660.183217350625
       x: [ 1.050e+00  1.050e+00  1.050e+00  1.050e+00]
     nit: 1
    nfev: 130
     jac: [-1.336e+03 -1.336e+03 -1.336e+03 -1.336e+03], result_bh.fun = 1.1712957802055646e-10, result_bh.x = [0.99999002 2.99999705 2.00163438 1.99837274]


In [22]:
# Sample inputs for the function
x_samples = [
    [ 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
    [0.999999, 0.999999, 0.999999, 0.999999]
]


# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function5(x)
    print(f'Function value for {x}:', function_value)

Function value for [1.0, 1.0, 1.0, 1.0]: 13912.0
Function value for [0.999999, 0.999999, 0.999999, 0.999999]: 13912.004735994127


# Function 4

In [65]:
import numpy as np
from scipy.optimize import differential_evolution, basinhopping

# Define the Ackley function
def function4(x, a=20, b=0.2, c=2*np.pi):
    """
    Ackley function for optimization tests in 4 dimensions.
    
    Args:
    - x: A list or array of 4 variables.
    - a, b, c: The Ackley function parameters.
    
    Returns:
    - The value of the Ackley function at the point x.
    """
    d = 4  # Dimensionality is 4
    sum_sq_term = -a * np.exp(-b * np.sqrt(sum(x_i ** 2 for x_i in x) / d))
    cos_term = -np.exp(sum(np.cos(c * x_i) for x_i in x) / d)
    return  (sum_sq_term + cos_term + a + np.exp(1))



# Set the bounds for each dimension
bounds = [(0, 1)] * 4  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function4, bounds)

# Perform basinhopping
result_bh = basinhopping(function4, [0.5] * 4, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")


result_de =  message: Optimization terminated successfully.
 success: True
     fun: 3.9968028886505635e-15
       x: [ 2.220e-16  1.832e-15  1.665e-15  1.110e-16]
     nit: 318
    nfev: 19145, result_bh.fun = 1.8399934758119838, result_bh.x = [-1.37487469e-08 -1.03543828e-08 -9.27878778e-01 -3.57881151e-09]


In [66]:
best_point = [1, 1, 1, 1]
exploitation_range = 0.05  # 5%

bounds_exploitation = [(x - x * exploitation_range, x + x * exploitation_range) for x in best_point]

# Perform differential evolution
result_de = differential_evolution(function4, bounds_exploitation)

# Perform basinhopping
result_bh = basinhopping(function4, [0.5] * 4, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")

result_de =  message: Optimization terminated successfully.
 success: True
     fun: 3.5744518772582414
       x: [ 9.685e-01  9.685e-01  9.685e-01  9.685e-01]
     nit: 2
    nfev: 205
     jac: [ 2.487e-06  1.421e-06  2.132e-06  4.263e-06], result_bh.fun = 1.8399934758119874, result_bh.x = [9.50957413e-09 6.62303838e-09 9.27878789e-01 9.17211386e-09]


In [68]:
# Sample inputs for the function
x_samples = [
    [0.999999, 0.999999, 0.999999, 0.999999],
    [2.220e-16, 1.832e-15, 1.665e-15, 1.110e-16],
    [9.685e-01, 9.685e-01, 9.685e-01, 9.685e-01]
]


# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function4(x)
    print(f'Function value for {x}:', - function_value)

Function value for [0.999999, 0.999999, 0.999999, 0.999999]: -3.625381663570679
Function value for [2.22e-16, 1.832e-15, 1.665e-15, 1.11e-16]: -3.9968028886505635e-15
Function value for [0.9685, 0.9685, 0.9685, 0.9685]: -3.5744519018271856


# Function 3

In [32]:
import numpy as np
from scipy.optimize import differential_evolution, basinhopping

#3D
def function3(x):
    # Only x2 and x3 are used, which are x[1] and x[2] in a 0-indexed Python list
    w2 = 1 + (x[1] - 1) / 4
    w3 = 1 + (x[2] - 1) / 4
    
    term1 = np.sin(np.pi * w2) ** 2
    term2 = (w2 - 1) ** 2 * (1 + 10 * np.sin(np.pi * w2 + 1) ** 2)
    term3 = (w3 - 1) ** 2 * (1 + np.sin(2 * np.pi * w3) ** 2)
    
    return term1 + term2 + term3



# Set the bounds for each dimension
bounds = [(0, 1)] * 3  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function3, bounds)

# Perform basinhopping
result_bh = basinhopping(function3, [0.5] * 3, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")




result_de =  message: Optimization terminated successfully.
 success: True
     fun: 1.4997597826618576e-32
       x: [ 4.755e-01  1.000e+00  1.000e+00]
     nit: 160
    nfev: 7249, result_bh.fun = 1.0031516607857986e-16, result_bh.x = [-3.89318862  1.          0.99999996]


In [34]:
best_point = [0.160101, 0.001449, 0.998173]
exploitation_range = 0.05  # 5%

bounds_exploitation = [(x - x * exploitation_range, x + x * exploitation_range) for x in best_point]

# Perform differential evolution
result_de = differential_evolution(function3, bounds_exploitation)

# Perform basinhopping
result_bh = basinhopping(function3, [0.5] * 3, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")



result_de =  message: Optimization terminated successfully.
 success: True
     fun: 0.5896840494583209
       x: [ 1.563e-01  1.521e-03  1.000e+00]
     nit: 1
    nfev: 102
     jac: [ 0.000e+00 -7.627e-01  1.443e-06], result_bh.fun = 5.643134565490133e-16, result_bh.x = [-0.91389089  0.99999999  0.99999991]


In [37]:
# Sample inputs for the function
x_samples = [
    [0.160101, 0.001449, 0.998173],
    [1.563e-01, 1.521e-03, 0.999999]
]


# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function3(x)
    print(f'Function value for {x}:', - function_value)

Function value for [0.160101, 0.001449, 0.998173]: -0.5897395168301832
Function value for [0.1563, 0.001521, 0.999999]: -0.5896843926711679


# Function 2

In [44]:
import numpy as np
from scipy.optimize import differential_evolution

def function2(x):
   
    x1, x2 = x  # Unpack the single iterable argument
    
    x1 = x1 * np.pi
    x2 = x2 * np.pi
    
    m = 10
    
    out1 = np.sin(x1) * (np.sin((x1**2) / np.pi))**(2 * m)
    out2 = np.sin(x2) * (np.sin((2 * x2**2) / np.pi))**(2 * m)
    noise = np.random.normal(0, 0.1)
    return - (out1 + out2 + noise) * 0.75  # negative sign for maximization


# Set the bounds for each dimension
bounds = [(0, 1)] * 2  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function2, bounds)

# Perform basinhopping
result_bh = basinhopping(function2, [0.5] * 2, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")


result_de =  message: Maximum number of iterations has been exceeded.
 success: False
     fun: -1.61632641516579
       x: [ 6.992e-01  5.020e-01]
     nit: 1000
    nfev: 30102, result_bh.fun = -0.7751648934045228, result_bh.x = [0.5 0.5]


In [45]:
best_point = [0.5, 0.5]
exploitation_range = 0.05  # 5%

bounds_exploitation = [(x - x * exploitation_range, x + x * exploitation_range) for x in best_point]

# Perform differential evolution
result_de = differential_evolution(function2, bounds_exploitation)

# Perform basinhopping
result_bh = basinhopping(function2, [0.5] * 2, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")


result_de =  message: Maximum number of iterations has been exceeded.
 success: False
     fun: -1.0375677714949216
       x: [ 5.117e-01  5.043e-01]
     nit: 1000
    nfev: 30081, result_bh.fun = -0.7636438587155229, result_bh.x = [0.50000993 0.50000876]


In [46]:
# Sample inputs for the function
x_samples = [
    [0.5       , 0.5       ],
       [0.70120661, 0.5       ],
       [0.70856593, 0.50295245],
       [0.70030882, 0.50029645],
       [0.70752778, 0.50555026],
       [0.72      , 0.51      ],
       [0.72      , 0.724482  ],
       [0.72      , 0.51      ],
       [0.70120661, 0.49999999],
       [0.69934552, 0.49910534],
       [0.69937559, 0.4987711 ],
       [0.69968659, 0.49869993],
       [0.69970324, 0.49888559],
       [0.25873889, 0.12258231],
       [0.970267  , 0.51      ],
       [0.75      , 0.09      ],
       [0.709     , 0.49      ],
       [0.69263693, 0.4959378 ],
       [0.5       , 0.50005   ],
       [0.70120661, 0.50005   ],
       [0.70272663, 0.49696603],
       [0.70061662, 0.49838217],
       [0.700162,0.501762]
]



# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function2(x)
    print(f'Function value for {x}:', function_value)
    
x_samples_array = np.array(x_samples)

# Compute the average of each dimension
dimension_averages = np.mean(x_samples_array, axis=0)
dimension_averages

Function value for [0.5, 0.5]: -0.8134999555195324
Function value for [0.70120661, 0.5]: -1.4159124751821288
Function value for [0.70856593, 0.50295245]: -1.3194437919598965
Function value for [0.70030882, 0.50029645]: -1.4601793253668778
Function value for [0.70752778, 0.50555026]: -1.298235885709711
Function value for [0.72, 0.51]: -1.2264920041814666
Function value for [0.72, 0.724482]: -0.5144276240692711
Function value for [0.72, 0.51]: -1.3840047986838344
Function value for [0.70120661, 0.49999999]: -1.4541719829896385
Function value for [0.69934552, 0.49910534]: -1.276553261187514
Function value for [0.69937559, 0.4987711]: -1.260469860563463
Function value for [0.69968659, 0.49869993]: -1.3756438001093594
Function value for [0.69970324, 0.49888559]: -1.3345874556959165
Function value for [0.25873889, 0.12258231]: 0.0720254485656969
Function value for [0.970267, 0.51]: -0.7185410750330229
Function value for [0.75, 0.09]: -0.32050422874104095
Function value for [0.709, 0.49]: -1.

array([0.68096876, 0.47628145])

# Function 1

In [57]:
import numpy as np
from scipy.optimize import differential_evolution, basinhopping

#2D
def function1(x):
    """
    Easom function for optimization tests in 2 dimensions.
    
    Args:
    - x: A list or array of 2 variables.
    
    Returns:
    - The value of the Easom function at the point x.
    """
    x1, x2 = x
    return -np.cos(x1) * np.cos(x2) * np.exp(-(x1 - np.pi)**2 - (x2 - np.pi)**2)*(-1000000)



# Set the bounds for each dimension
bounds = [(0, 1)] * 2  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function1, bounds)

# Perform basinhopping
result_bh = basinhopping(function1, [0.5] * 2, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")



result_de =  message: Optimization terminated successfully.
 success: True
     fun: 0.0026752879910742432
       x: [ 0.000e+00  0.000e+00]
     nit: 24
    nfev: 756
     jac: [ 1.681e-02  1.681e-02], result_bh.fun = -4.2064446675743855e-08, result_bh.x = [-1.6247151   1.01524699]


In [58]:

best_point = [0.62854, 0.62854]
exploitation_range = 0.05  # 5%

bounds_exploitation = [(x - x * exploitation_range, x + x * exploitation_range) for x in best_point]

# Perform differential evolution
result_de = differential_evolution(function1, bounds_exploitation)

# Perform basinhopping
result_bh = basinhopping(function1, [0.5] * 2, niter=200)  # start at the middle of the bounds

print(f"result_de = {result_de}, result_bh.fun = {result_bh.fun}, result_bh.x = {result_bh.x}")



result_de =  message: Optimization terminated successfully.
 success: True
     fun: 1.62704386780575
       x: [ 5.971e-01  5.971e-01]
     nit: 14
    nfev: 456
     jac: [ 7.174e+00  7.174e+00], result_bh.fun = -9.02243776026091e-10, result_bh.x = [ 0.47821747 -2.01427697]


In [60]:

# Sample inputs for the function
x_samples = [
    [0.62854, 0.62854],
    [0.5, 0.5],
    [5.971e-01, 5.971e-01]
]


# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function1(x)
    print(f'Function value for {x}:', function_value)

Function value for [0.62854, 0.62854]: 2.1392401136209394
Function value for [0.5, 0.5]: 0.6691939049188014
Function value for [0.5971, 0.5971]: 1.626857360780848
