In [11]:
from scipy.optimize import differential_evolution, basinhopping

# Define the objective function as provided in the user's image
def function8(x):
    out = -2 * (x[0] - 0.1)**2
    out += -1 * (x[1] - 0.15)**2
    out += -3 * (x[2] - 0.13)**2
    out += -1 * (x[3] - 0.15)**2
    out += -0.5 * (x[4] - 0.8)**2
    out += -1 * (x[5] - 0.5)**2
    out += -2 * (x[6] - 0.2)**2
    out += -0.1 * (x[7] - 0.6)**2
    return out + 10

# Set the bounds for each dimension
bounds = [(0, 1)] * 8  # assuming the variables are bounded between 0 and 1

# Perform differential evolution
result_de = differential_evolution(function8, bounds)

# Perform basinhopping
result_bh = basinhopping(function8, [0.5] * 8, niter=200)  # start at the middle of the bounds

result_de, result_bh.fun, result_bh.x



( message: Optimization terminated successfully.
  success: True
      fun: 2.778299999999999
        x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  0.000e+00
             0.000e+00  1.000e+00  0.000e+00]
      nit: 83
     nfev: 10098
      jac: [-3.600e+00 -1.700e+00 -5.220e+00 -1.700e+00  8.000e-01
             1.000e+00 -3.200e+00  1.200e-01],
 -1.7499604271971958e+25,
 array([ 3.68952760e+07,  8.10047148e+06, -2.16893163e+12,  1.84032906e+12,
        -1.74163846e+06, -2.75404585e+03,  2.77150904e+07, -2.20368002e+04]))

In [2]:
# Sample inputs for the function
x_samples = [
    [0.1, 0.15, 0.13, 0.15, 0.8, 0.5, 0.2, 0.6]
]

# Define the objective function as provided in the user's image
def function8(x):
    out = -2 * (x[0] - 0.1)**2
    out += -1 * (x[1] - 0.15)**2
    out += -3 * (x[2] - 0.13)**2
    out += -1 * (x[3] - 0.15)**2
    out += -0.5 * (x[4] - 0.8)**2
    out += -1 * (x[5] - 0.5)**2
    out += -2 * (x[6] - 0.2)**2
    out += -0.1 * (x[7] - 0.6)**2
    return out + 10

# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function8(x)
    print(f'Function value for {x}:', function_value)

Function value for [0.1, 0.15, 0.13, 0.15, 0.8, 0.5, 0.2, 0.6]: 10.0


In [9]:
import numpy as np
from scipy.optimize import differential_evolution

# Define function6 from the image provided with added noise
def function6(x):
    out = -1 * np.abs(x[0] - 0.42)
    out += -1 * np.abs(x[1] - 0.36)
    out += -1 * np.abs(x[2] - 0.65)
    out += -1 * np.abs(x[3] - 0.77)
    out += -1 * np.abs(x[4] - 0.1)
    return out + np.random.normal(0, 0.05)

# Since we are looking for global optima and the function is noisy,
# we should run the optimizer several times to ensure we find a robust solution.
# We'll define the bounds for the optimization (assuming they are [0, 1] for each variable)
bounds = [(0, 1), (0, 1), (0, 1), (0, 1), (0, 1)]

# Perform the optimization using Differential Evolution
# Due to the stochastic nature of the function, it's recommended to increase the number of iterations and
# the population size to get a more accurate result.
result = differential_evolution(function6, bounds, maxiter=1000, popsize=25)

result.fun, result.x



(-3.6196662283652015,
 array([0.99377466, 0.99638798, 0.01748738, 0.00609115, 0.98995587]))

In [26]:
import numpy as np
from scipy.optimize import differential_evolution

# Define function6 from the image provided with added noise
def function6(x):
    out = -1 * np.abs(x[0] - 0.42)
    out += -1 * np.abs(x[1] - 0.36)
    out += -1 * np.abs(x[2] - 0.65)
    out += -1 * np.abs(x[3] - 0.77)
    out += -1 * np.abs(x[4] - 0.1)
    return out + np.random.normal(0, 0.05)

# New bounds based on the optimization results
bounds = [(0.99, 1.0),  # New bound for x[0]
          (0.97, 1.0),  # New bound for x[1]
          (0.0, 0.05),  # New bound for x[2]
          (0.0, 0.05),  # New bound for x[3]
          (0.97, 1.0)]  # New bound for x[4]

# Perform the optimization using Differential Evolution with the new bounds
result = differential_evolution(function6, bounds, maxiter=10000, popsize=1000)

result.fun, result.x

(-3.747301308472089,
 array([0.99981685, 0.99954416, 0.00292226, 0.00500321, 0.99681116]))

In [27]:
# Sample inputs for the function
x_samples = [
    [0.999999, 0.999031, 0.003125, 0.      , 0.992245],
    [0.99572389, 0.97373593, 0.0027237 , 0.00847641, 0.98693783],
    [0.99881636, 0.99261304, 0.01461281, 0.03374769, 0.97225405],
    [0.99377466, 0.99638798, 0.01748738, 0.00609115, 0.98995587],
    [9.98270807e-01, 9.90335660e-01, 1.10511377e-02, 7.30842077e-04,
        9.89654110e-01],
    [0.99704482, 0.99243628, 0.01288065, 0.02471047, 0.99574526],
    [0.99333672, 0.99717332, 0.00717687, 0.01454184, 0.98702172],
    [9.94885225e-01, 9.82954887e-01, 2.14005077e-02, 9.82798925e-04,
        9.99218603e-01],
    [9.92826750e-01, 9.78115507e-01, 3.58238894e-04, 2.45893403e-02,
        9.94932078e-01],
    [0.99185211, 0.99143621, 0.00726933, 0.00358599, 0.99696841],
    [0.99498962, 0.99866151, 0.00269336, 0.01282776, 0.99915352],
    [0.99981685, 0.99954416, 0.00292226, 0.00500321, 0.99681116]
]

# Define function6 from the image provided with added noise
def function6(x):
    out = -1 * np.abs(x[0] - 0.42)
    out += -1 * np.abs(x[1] - 0.36)
    out += -1 * np.abs(x[2] - 0.65)
    out += -1 * np.abs(x[3] - 0.77)
    out += -1 * np.abs(x[4] - 0.1)
    return out + np.random.normal(0, 0.05)
    return out + 10

# Loop over the sample inputs and call michalewicz_function for each
for x in x_samples:
    function_value = function6(x)
    print(f'Function value for {x}:', function_value)

Function value for [0.999999, 0.999031, 0.003125, 0.0, 0.992245]: -3.4022970623605664
Function value for [0.99572389, 0.97373593, 0.0027237, 0.00847641, 0.98693783]: -3.3813290639079887
Function value for [0.99881636, 0.99261304, 0.01461281, 0.03374769, 0.97225405]: -3.481512053506839
Function value for [0.99377466, 0.99638798, 0.01748738, 0.00609115, 0.98995587]: -3.446237245161924
Function value for [0.998270807, 0.99033566, 0.0110511377, 0.000730842077, 0.98965411]: -3.5634089316493553
Function value for [0.99704482, 0.99243628, 0.01288065, 0.02471047, 0.99574526]: -3.4852649398835815
Function value for [0.99333672, 0.99717332, 0.00717687, 0.01454184, 0.98702172]: -3.5041072044652597
Function value for [0.994885225, 0.982954887, 0.0214005077, 0.000982798925, 0.999218603]: -3.4362843532981877
Function value for [0.99282675, 0.978115507, 0.000358238894, 0.0245893403, 0.994932078]: -3.4232350282149833
Function value for [0.99185211, 0.99143621, 0.00726933, 0.00358599, 0.99696841]: -3.4