In [6]:
import numpy as np
from scipy.stats import bernoulli

## Q1. Load the file "sample_1.npy" and convert it to a binary array
- This is simply a Numpy array of previous tosses of a single coin
- Convert it to 0/1's instead of H/T's

In [7]:
sample = np.load('sample_1.npy') #search for how to load a ".npy" file

In [8]:
sample = np.array ([1 if x=="H" else 0 for x in sample ]) #convert 'sample' to a binary array
print(sample[:10]) 

[1 1 1 1 0 0 1 0 1 1]


## Q2. Answer the following
- How many coin tosses do we have recorded?
- How many "heads" are there in total?
- What is the maximum number of consecutive "heads" appearing together?

In [9]:
n = len(sample) #total coin tosses
print("n = ", n)

n =  1000


In [10]:
heads_total = np.sum(sample) #number of heads
print("heads_total = ", heads_total)

heads_total =  620


In [11]:
from itertools import groupby
max_running = max(len(list(v)) for k,v in groupby(sample) if k==1) #number of max running heads
print("max_running = ", max_running)

max_running =  15


## Q3: Find the MLE estimate for $\theta$ 
- $\theta$ is the probability of head showing in a single toss

In [12]:
theta_hat = heads_total / n  #MLE estimate
print("MLE estimate", theta_hat)

MLE estimate 0.62


## Q4: Load the file "sample_2.npy"
- You analyze a new coin, where there are 1 million tosses of the same coin where the true $\theta$ value is $0.97$
- Here "1" stands for "head"

In [13]:
sample_2 = np.load('sample_2.npy') #load the file

## Q5: After how many tosses, your MLE estimate is within $[0.97001, 0.96999]$ 
- report the minimum number that satisfies this

In [24]:
sample_2[:100]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [21]:
np.mean(sample_2)

0.969741

In [30]:
#(np.arange(1,pow(10,6)+ 1)) =[1,2,3....1000000]
ratios = np.cumsum(sample_2) / (np.arange(1,pow(10,6)+ 1)) #running ratios. ratios[10] would give us hat_theta(9)
#ratios = ... #first compute the running ratios
#ratios[:1000]

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [31]:
for index, value in np.ndenumerate(ratios):
    if 0.96999 <= value <= 0.97001:
        #print (f'index is {index} and value is {value})
        break
print("smallest_accurate_n", index)        
#smallest_accurate_n = ... #report the answer

smallest_accurate_n (5298,)


## Submission:
- Please submit your answers for `n`, `heads_total`, `max_running`, `theta_hat` for the questions related to "sample_1.npy"
- Please submit your answer for `smallest_accurate_n` for the question replated to "sample_2.npy"